#!/bin/bash

### BEGIN INIT INFO
# Provides:          eaichefito-api
# Author:            Team E ai Chefito
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Conjunto de servicos para integracao E ai Chefito x Aplicacoes de terceiros.
# Description:       Ativa o server.js do eaichefito-api.
### END INIT INFO


# Exporta o diretorio do binario e dos modulos NodeJs.
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$PATH:/opt/mean/node_modules
NODE_ENVIROMENT=production

# Define os dados do arquivo auxiliar para armazenar o pid do processo.
SERVER=eacchefito-api
PID_FILE=/var/run/$SERVER.pid

# Diretorio de instalacao do Nerus App API.
DIR=/var/www/$SERVER

start() {
    export NODE_ENV=$NODE_ENVIROMENT
    export HOME=/root
    touch $PID_FILE
    cd $DIR
    exec forever --pidFile $PID_FILE start -a server.js
}

stop() {
    export HOME=/root
    if [ -f $PID_FILE ]; then
        read PID < $PID_FILE
        if [ "$PID" != "" ]; then
            cd $DIR
            exec forever --pidFile $PID_FILE stop server.js
        fi
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
    ;;

    stop)
        stop
    ;;

    restart)
        restart
    ;;

    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0